[versions]
target-sdk = "33"
compile-sdk = "33"
min-sdk = "21"
#libraries
core_version = "1.9.0"
appcompat_version = "1.6.0"
constraintlayout_version = "2.1.4"
navigation_version = "2.5.3"
lifecycle_version = "2.5.1"
legacy_version = "1.0.0"
material_version = "1.7.0"
hilt_version = "2.44.2"
retrofit_version = "2.9.0"
coil_version = "2.2.2"
leakcanary_version = "2.10"
datastore_version = "1.0.0"
#tests
junit_version = "4.13.2"
junit_ext_version = "1.1.5"
espresso_core_version = "3.5.1"
okhttp_version = "4.10.0"
mockito_version= "3.0.0"
mockito_kotlin_version = "4.0.0"
truth_version = "1.1.3"
turbine_version = "0.9.0"
#plugins
gradle_plugin = "7.4.0"
kotlin_version = "1.7.21"

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core_version" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat_version" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout_version" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation_version" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation_version" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle_version" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle_version" }
androidx-legacy = {module = "androidx.legacy:legacy-support-v4",version.ref = "legacy_version"}
androidx-datastore={module = "androidx.datastore:datastore-preferences",version.ref = "datastore_version"}
android-material = { module = "com.google.android.material:material", version.ref = "material_version" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt_version" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt_version" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit_version" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit_version" }
coil = { module = "io.coil-kt:coil", version.ref = "coil_version" }
leak-canary = {module = "com.squareup.leakcanary:leakcanary-android",version.ref = "leakcanary_version"}

#tests
test-junit = { module = "junit:junit", version.ref = "junit_version" }
test-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit_ext_version" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso_core_version" }
test-okhttp = {module = "com.squareup.okhttp3:mockwebserver",version.ref = "okhttp_version"}
test-mockito = {module = "org.mockito:mockito-inline",version.ref="mockito_version"}
test-mockito-kotlin = {module = "org.mockito.kotlin:mockito-kotlin",version.ref = "mockito_kotlin_version"}
test-truth = {module = "com.google.truth:truth",version.ref = "truth_version"}
test-turbine = {module = "app.cash.turbine:turbine",version.ref = "turbine_version"}
[bundles]
navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]
retrofit = ["retrofit", "retrofit-moshi"]
lifecycle = ["androidx-livedata","androidx-viewmodel","androidx-legacy"]
default = ["androidx-core","androidx-appcompat","android-material"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle_plugin" }
android-library = { id = "com.android.library", version.ref = "gradle_plugin" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin_version" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin_version" }
androidx-navigation = { id = "androidx.navigation.safeargs", version.ref = "navigation_version" }
